create table user(
	id int not null primary key auto_increment,
	user_session varchar(100),
	user_code	varchar(100),
	access_token varchar(250),
	expires_in int,
	uid bigint unsigned,
	created_time timestamp
);

create table weibo(
	id int not null primary key auto_increment,
	weibo_id bigint unsigned ,
	idstr	varchar(50),
	created_at varchar(50),
	weibo_text varchar(1000),
	weibo_source varchar(100),
	favorited char(1),
	truncated char(1),
	in_reply_to_status_id varchar(100),
	in_reply_to_user_id	varchar(100),
	in_reply_to_screen_name varchar(50),
	thumbnail_pic	varchar(50),
	bmiddle_pic		varchar(50),
	orginal_pic		varchar(50),
	geo_id int,
	mid bigint unsigned,
	reposts_count int,
	comments_count int,
	attitudes_count int,
	annotation_id int,
	author_id int,
	retweeted_weibo_id bigint unsigned,
	mlevel int,
	visible int,
	pic_urls varchar(500),	
	created_time timestamp
);

create table geo(
	id int not null primary key auto_increment,
	longitude varchar(50),
	latitude varchar(50),
	city varchar(50),
	province varchar(50),
	city_name varchar(50),
	province_name varchar(50),
	address	varchar(250),
	pinyin	varchar(250),
	more	varchar(500),
	created_time timestamp
);

create table author(
	id int not null primary key auto_increment,
	origin_id bigint unsigned,
	idstr varchar(50),
	screen_name varchar(100),
	author_name	varchar(100),
	province	int,
	city		int,
	location  varchar(250),
	description	varchar(500),
	url		varchar(50),
	profile_image_url varchar(50),
	profile_url	varchar(50),
	domain	varchar(50),
	weihao	varchar(50),
	gender	char(1),
	followers_count int,
	friends_count	int,
	statuses_count	int,
	favourites_count int,
	created_at	varchar(50),
	following	char(1),
	allow_all_act_msg char(1),
	geo_enabled	char(1),
	verified	char(1),
	verified_type int,
	remark	varchar(50),
	weibo_id bigint unsigned,
	allow_all_comment char(1),
	avatar_large	varchar(50),
	avatar_hd		varchar(50),
	verified_reason	varchar(250),
	follow_me	char(1),
	online_status	int,
	bi_followers_count int,
	lang	varchar(10),
	created_time timestamp
)